from fastapi import APIRouter

router = APIRouter(prefix="/api", tags=["help"])


@router.get("/help")
async def get_help():
    return {
        "api_version": "0.1.0",
        "base_url": "/api",
        "authentication": {
            "type": "Bearer Token",
            "header": "Authorization: Bearer <token>",
            "obtain_token": "POST /api/token",
        },
        "endpoints": [
            {
                "method": "POST",
                "path": "/api/register",
                "auth": False,
                "description": "Register a new user",
                "body": {"username": "string (3-50 chars)", "password": "string (8-100 chars)"},
                "response": {"id": "string", "username": "string", "display_name": "string|null", "created_at": "datetime"},
            },
            {
                "method": "POST",
                "path": "/api/token",
                "auth": False,
                "description": "Authenticate and obtain an access token",
                "body": {"username": "string", "password": "string"},
                "response": {"access_token": "string", "token_type": "bearer", "expires_in": "int (seconds)"},
            },
            {
                "method": "GET",
                "path": "/api/me",
                "auth": True,
                "description": "Get current authenticated user profile",
                "response": {"id": "string", "username": "string", "display_name": "string|null", "created_at": "datetime"},
            },
            {
                "method": "PUT",
                "path": "/api/me/settings",
                "auth": True,
                "description": "Update current user settings and display name",
                "body": {"display_name": "string|null (max 100)", "settings": "object|null"},
                "response": {"id": "string", "username": "string", "display_name": "string|null", "created_at": "datetime"},
            },
            {
                "method": "GET",
                "path": "/api/friends",
                "auth": True,
                "description": "List all friends of the current user",
                "response": [{"id": "string", "username": "string", "display_name": "string|null", "status": "string", "since": "datetime"}],
            },
            {
                "method": "POST",
                "path": "/api/friends",
                "auth": True,
                "description": "Add a user as a friend",
                "body": {"friend_id": "string"},
                "response": {"id": "string", "username": "string", "display_name": "string|null", "status": "string", "since": "datetime"},
            },
            {
                "method": "DELETE",
                "path": "/api/friends/{friend_id}",
                "auth": True,
                "description": "Remove a friend",
                "params": {"friend_id": "string (path)"},
                "response": "204 No Content",
            },
            {
                "method": "GET",
                "path": "/api/workspaces",
                "auth": True,
                "description": "List all workspaces the current user belongs to",
                "response": [{"id": "string", "name": "string", "owner_id": "string", "member_count": "int", "created_at": "datetime"}],
            },
            {
                "method": "POST",
                "path": "/api/workspaces",
                "auth": True,
                "description": "Create a new workspace",
                "body": {"name": "string (1-100 chars)"},
                "response": {"id": "string", "name": "string", "owner_id": "string", "member_count": "int", "created_at": "datetime"},
            },
            {
                "method": "POST",
                "path": "/api/workspaces/{workspace_id}/join",
                "auth": True,
                "description": "Join an existing workspace",
                "params": {"workspace_id": "string (path)"},
                "response": {"id": "string", "name": "string", "owner_id": "string", "member_count": "int", "created_at": "datetime"},
            },
            {
                "method": "DELETE",
                "path": "/api/workspaces/{workspace_id}",
                "auth": True,
                "description": "Delete a workspace (owner only)",
                "params": {"workspace_id": "string (path)"},
                "response": "204 No Content",
            },
            {
                "method": "GET",
                "path": "/api/workspaces/{workspace_id}/rooms",
                "auth": True,
                "description": "List all rooms in a workspace",
                "params": {"workspace_id": "string (path)"},
                "response": [{"id": "string", "workspace_id": "string", "name": "string", "created_by": "string", "created_at": "datetime"}],
            },
            {
                "method": "POST",
                "path": "/api/workspaces/{workspace_id}/rooms",
                "auth": True,
                "description": "Create a room in a workspace",
                "params": {"workspace_id": "string (path)"},
                "body": {"name": "string (1-100 chars)"},
                "response": {"id": "string", "workspace_id": "string", "name": "string", "created_by": "string", "created_at": "datetime"},
            },
            {
                "method": "DELETE",
                "path": "/api/workspaces/{workspace_id}/rooms/{room_id}",
                "auth": True,
                "description": "Delete a room (workspace owner only)",
                "params": {"workspace_id": "string (path)", "room_id": "string (path)"},
                "response": "204 No Content",
            },
            {
                "method": "GET",
                "path": "/api/notifications",
                "auth": True,
                "description": "List notifications for the current user",
                "query": {"unread": "boolean (default false)"},
                "response": [{"id": "int", "type": "string", "payload": "object", "read": "boolean", "created_at": "datetime"}],
            },
            {
                "method": "PUT",
                "path": "/api/notifications/{notification_id}/read",
                "auth": True,
                "description": "Mark a notification as read",
                "params": {"notification_id": "int (path)"},
                "response": {"id": "int", "type": "string", "payload": "object", "read": "boolean", "created_at": "datetime"},
            },
            {
                "method": "GET",
                "path": "/api/help",
                "auth": False,
                "description": "Get this API reference with all available endpoints",
            },
        ],
    }
